name: Create iOS Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version (e.g. 1.0.1)'
        required: true

jobs:
  create-release:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure Git
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Create release branch and bump version
        run: |
          VERSION=${{ github.event.inputs.version }}
          git fetch origin develop
          git checkout -b release/release-${VERSION} origin/develop

          # Set version using agvtool
          xcrun agvtool new-marketing-version ${VERSION}

          git add .
          git commit -m "Bump version to ${VERSION}"
          git push origin release/release-${VERSION}

      - name: Create Pull Request to master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr create \
            --base master \
            --head release/release-${{ github.event.inputs.version }} \
            --title "Release ${{ github.event.inputs.version }}" \
            --body "Auto-created release branch for version ${{ github.event.inputs.version }}"
